#!/usr/bin/env python3
"""
generate_sitemap.py — Maya's Homes sitemap generator.

Walks the workspace for *.html pages, derives each canonical URL, pairs
every English page with its Portuguese (/pt/) alternate, and emits a
sitemap.xml with xhtml:link hreflang annotations per Google's
multilingual-sitemap spec.

Pages carrying <meta name="robots" content="noindex..."> are EXCLUDED —
listing a noindex URL in a sitemap triggers a "Submitted URL marked
noindex" warning in Google Search Console, which is the opposite of what
a sitemap is for. (privacy, terms, contact/thanks, thank-you are all
noindex on this site.) Run with --include-noindex to override.

Usage:
    python3 scripts/generate_sitemap.py            # write sitemap.xml
    python3 scripts/generate_sitemap.py --dry-run  # print, don't write
    python3 scripts/generate_sitemap.py --include-noindex
"""

import argparse
import datetime
import re
import sys
from pathlib import Path

DOMAIN = "https://mayashomes.com"
ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "sitemap.xml"

NOINDEX_RE = re.compile(r'name=["\']robots["\']\s+content=["\'][^"\']*noindex', re.I)

# Per-path-pattern priority + changefreq. First match wins; order matters.
RULES = [
    (re.compile(r"^/(pt/)?$"),                      "1.0", "weekly"),   # homepages
    (re.compile(r"^/(pt/)?projects/$"),             "0.9", "monthly"),  # portfolio index
    (re.compile(r"^/(pt/)?services/$"),             "0.9", "monthly"),  # services index
    (re.compile(r"^/(pt/)?services/.+"),            "0.7", "monthly"),  # sub-services
    (re.compile(r"^/(pt/)?profile/$"),              "0.8", "monthly"),
    (re.compile(r"^/(pt/)?contact/$"),              "0.8", "monthly"),
    (re.compile(r"^/(pt/)?projects/monte-estoril"), "0.6", "monthly"),  # in-progress
    (re.compile(r"^/(pt/)?projects/.+"),            "0.8", "yearly"),   # finished projects
    (re.compile(r"^/(pt/)?journal/.+"),             "0.7", "yearly"),   # articles
    (re.compile(r"^/(pt/)?journal/$"),              "0.7", "monthly"),
    (re.compile(r"^/(pt/)?(privacy|terms)/$"),      "0.3", "yearly"),   # legal
]
DEFAULT_PRIORITY, DEFAULT_CHANGEFREQ = "0.5", "monthly"


def path_to_url_path(html_path: Path) -> str:
    """./profile/index.html -> /profile/ ; ./index.html -> / ; ./pt/index.html -> /pt/"""
    rel = html_path.relative_to(ROOT).as_posix()
    rel = re.sub(r"index\.html$", "", rel)   # drop filename
    if not rel.startswith("/"):
        rel = "/" + rel
    return rel


def is_noindex(html_path: Path) -> bool:
    head = html_path.read_text(encoding="utf-8", errors="ignore")[:4000]
    return bool(NOINDEX_RE.search(head))


def alternates(url_path: str) -> dict:
    """Return {hreflang: absolute_url} for a given url path."""
    if url_path.startswith("/pt/"):
        en_path = url_path[3:] or "/"      # strip '/pt'
        pt_path = url_path
    elif url_path == "/pt":
        en_path, pt_path = "/", "/pt/"
    else:
        en_path = url_path
        pt_path = "/pt" + url_path
    return {
        "en": DOMAIN + en_path,
        "pt-PT": DOMAIN + pt_path,
        "x-default": DOMAIN + en_path,
    }


def priority_changefreq(url_path: str):
    for pattern, prio, freq in RULES:
        if pattern.match(url_path):
            return prio, freq
    return DEFAULT_PRIORITY, DEFAULT_CHANGEFREQ


def build(include_noindex: bool):
    pages = sorted(ROOT.rglob("index.html"))
    pages = [p for p in pages if "node_modules" not in p.parts]

    included, excluded = [], []
    for p in pages:
        if not include_noindex and is_noindex(p):
            excluded.append(path_to_url_path(p))
            continue
        included.append(path_to_url_path(p))

    # Stable, human-friendly ordering: by priority desc, then path.
    included.sort(key=lambda u: (-float(priority_changefreq(u)[0]), u))

    today = datetime.date.today().isoformat()
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
        '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
        "",
        f"  <!-- Generated by scripts/generate_sitemap.py on {today}.",
        f"       {len(included)} indexable URLs. Do not hand-edit — re-run the script. -->",
        "",
    ]
    for url_path in included:
        loc = DOMAIN + url_path
        prio, freq = priority_changefreq(url_path)
        alts = alternates(url_path)
        lines.append("  <url>")
        lines.append(f"    <loc>{loc}</loc>")
        lines.append(f"    <lastmod>{today}</lastmod>")
        lines.append(f"    <changefreq>{freq}</changefreq>")
        lines.append(f"    <priority>{prio}</priority>")
        for hreflang, href in alts.items():
            lines.append(
                f'    <xhtml:link rel="alternate" hreflang="{hreflang}" href="{href}" />'
            )
        lines.append("  </url>")
    lines.append("")
    lines.append("</urlset>")
    return "\n".join(lines) + "\n", included, excluded


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--include-noindex", action="store_true")
    args = ap.parse_args()

    xml, included, excluded = build(args.include_noindex)

    if args.dry_run:
        sys.stdout.write(xml)
    else:
        OUTPUT.write_text(xml, encoding="utf-8")
        print(f"Wrote {OUTPUT.relative_to(ROOT)}")

    print(f"\nIncluded {len(included)} URLs.")
    if excluded:
        print(f"Excluded {len(excluded)} noindex pages (use --include-noindex to force):")
        for u in sorted(excluded):
            print(f"  - {u}")


if __name__ == "__main__":
    main()
